// Code generated by carrier, DO NOT EDIT.
package carrier

import (
	"github.com/Yiling-J/carrier/integration/carrier/factory"
)

type Factory struct {
	groupFactory *factory.GroupFactory

	userFactory *factory.UserFactory
}

func GroupMetaFactory() *factory.GroupMetaFactory {
	return &factory.GroupMetaFactory{}
}
func (f *Factory) SetGroupFactory(c *factory.GroupFactory) *Factory {
	f.groupFactory = c
	return f
}

func (f *Factory) GroupFactory() *factory.GroupFactory {
	return f.groupFactory
}

func UserMetaFactory() *factory.UserMetaFactory {
	return &factory.UserMetaFactory{}
}
func (f *Factory) SetUserFactory(c *factory.UserFactory) *Factory {
	f.userFactory = c
	return f
}

func (f *Factory) UserFactory() *factory.UserFactory {
	return f.userFactory
}
