// Code generated by carrier, DO NOT EDIT.
package factory

import (
	"github.com/Yiling-J/carrier/integration/model"

	"context"
)

type groupMutation struct {
	nameType int
	nameFunc func(ctx context.Context, i *model.Group, c int) error

	categoryType int
	categoryFunc func(ctx context.Context, i *model.Group, c int) error

	beforeCreateFunc func(ctx context.Context, i *model.Group) error
	afterCreateFunc  func(ctx context.Context, i *model.Group) error
}
type GroupMetaFactory struct {
	mutation groupMutation
}
type groupTrait struct {
	mutation groupMutation
	updates  []func(m *groupMutation)
}

func GroupTrait() *groupTrait {
	return &groupTrait{}
}
func (*groupMutation) beforeCreateMutateFunc(fn func(ctx context.Context, i *model.Group) error) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.beforeCreateFunc = fn
	}
}
func (*groupMutation) afterCreateMutateFunc(fn func(ctx context.Context, i *model.Group) error) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.afterCreateFunc = fn
	}
}

func (*groupMutation) nameSequenceMutateFunc(fn func(ctx context.Context, i int) (string, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.nameType = TypeSequence
		m.nameFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx, c)
			if err != nil {
				return err
			}

			i.Name = value
			return nil
		}
	}
}
func (*groupMutation) nameLazyMutateFunc(fn func(ctx context.Context, i *model.Group) (string, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.nameType = TypeLazy
		m.nameFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx, i)
			if err != nil {
				return err
			}

			i.Name = value
			return nil
		}
	}
}
func (*groupMutation) nameDefaultMutateFunc(v string) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.nameType = TypeDefault
		m.nameFunc = func(ctx context.Context, i *model.Group, c int) error {

			i.Name = v
			return nil
		}
	}
}
func (*groupMutation) nameFactoryMutateFunc(fn func(ctx context.Context) (string, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.nameType = TypeFactory
		m.nameFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx)
			if err != nil {
				return err
			}

			i.Name = value

			return nil
		}
	}
}

// SetNameSequence register a function which accept a sequence counter and set return value to Name field
func (f *GroupMetaFactory) SetNameSequence(fn func(ctx context.Context, i int) (string, error)) *GroupMetaFactory {
	f.mutation.nameSequenceMutateFunc(fn)(&f.mutation)
	return f
}

// SetNameLazy register a function which accept the build struct and set return value to Name field
func (f *GroupMetaFactory) SetNameLazy(fn func(ctx context.Context, i *model.Group) (string, error)) *GroupMetaFactory {
	f.mutation.nameLazyMutateFunc(fn)(&f.mutation)
	return f
}

// SetNameDefault assign a default value to Name field
func (f *GroupMetaFactory) SetNameDefault(v string) *GroupMetaFactory {
	f.mutation.nameDefaultMutateFunc(v)(&f.mutation)
	return f
}

// SetNameFactory register a factory function and assign return value to Name, you can also use related factory's Create/CreateV as input function here
func (f *GroupMetaFactory) SetNameFactory(fn func(ctx context.Context) (string, error)) *GroupMetaFactory {
	f.mutation.nameFactoryMutateFunc(fn)(&f.mutation)
	return f
}

// SetNameSequence register a function which accept a sequence counter and set return value to Name field
func (t *groupTrait) SetNameSequence(fn func(ctx context.Context, i int) (string, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.nameSequenceMutateFunc(fn))
	return t
}

// SetNameLazy register a function which accept the build struct and set return value to Name field
func (t *groupTrait) SetNameLazy(fn func(ctx context.Context, i *model.Group) (string, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.nameLazyMutateFunc(fn))
	return t
}

// SetNameDefault assign a default value to Name field
func (t *groupTrait) SetNameDefault(v string) *groupTrait {
	t.updates = append(t.updates, t.mutation.nameDefaultMutateFunc(v))
	return t
}

// SetNameFactory register a factory function and assign return value to Name, you can also use related factory's Create/CreateV as input function here
func (t *groupTrait) SetNameFactory(fn func(ctx context.Context) (string, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.nameFactoryMutateFunc(fn))
	return t
}

func (*groupMutation) categorySequenceMutateFunc(fn func(ctx context.Context, i int) (model.GroupCategory, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.categoryType = TypeSequence
		m.categoryFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx, c)
			if err != nil {
				return err
			}

			i.Category = value
			return nil
		}
	}
}
func (*groupMutation) categoryLazyMutateFunc(fn func(ctx context.Context, i *model.Group) (model.GroupCategory, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.categoryType = TypeLazy
		m.categoryFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx, i)
			if err != nil {
				return err
			}

			i.Category = value
			return nil
		}
	}
}
func (*groupMutation) categoryDefaultMutateFunc(v model.GroupCategory) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.categoryType = TypeDefault
		m.categoryFunc = func(ctx context.Context, i *model.Group, c int) error {

			i.Category = v
			return nil
		}
	}
}
func (*groupMutation) categoryFactoryMutateFunc(fn func(ctx context.Context) (model.GroupCategory, error)) func(m *groupMutation) {
	return func(m *groupMutation) {
		m.categoryType = TypeFactory
		m.categoryFunc = func(ctx context.Context, i *model.Group, c int) error {
			if fn == nil {
				return nil
			}
			value, err := fn(ctx)
			if err != nil {
				return err
			}

			i.Category = value

			return nil
		}
	}
}

// SetCategorySequence register a function which accept a sequence counter and set return value to Category field
func (f *GroupMetaFactory) SetCategorySequence(fn func(ctx context.Context, i int) (model.GroupCategory, error)) *GroupMetaFactory {
	f.mutation.categorySequenceMutateFunc(fn)(&f.mutation)
	return f
}

// SetCategoryLazy register a function which accept the build struct and set return value to Category field
func (f *GroupMetaFactory) SetCategoryLazy(fn func(ctx context.Context, i *model.Group) (model.GroupCategory, error)) *GroupMetaFactory {
	f.mutation.categoryLazyMutateFunc(fn)(&f.mutation)
	return f
}

// SetCategoryDefault assign a default value to Category field
func (f *GroupMetaFactory) SetCategoryDefault(v model.GroupCategory) *GroupMetaFactory {
	f.mutation.categoryDefaultMutateFunc(v)(&f.mutation)
	return f
}

// SetCategoryFactory register a factory function and assign return value to Category, you can also use related factory's Create/CreateV as input function here
func (f *GroupMetaFactory) SetCategoryFactory(fn func(ctx context.Context) (model.GroupCategory, error)) *GroupMetaFactory {
	f.mutation.categoryFactoryMutateFunc(fn)(&f.mutation)
	return f
}

// SetCategorySequence register a function which accept a sequence counter and set return value to Category field
func (t *groupTrait) SetCategorySequence(fn func(ctx context.Context, i int) (model.GroupCategory, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.categorySequenceMutateFunc(fn))
	return t
}

// SetCategoryLazy register a function which accept the build struct and set return value to Category field
func (t *groupTrait) SetCategoryLazy(fn func(ctx context.Context, i *model.Group) (model.GroupCategory, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.categoryLazyMutateFunc(fn))
	return t
}

// SetCategoryDefault assign a default value to Category field
func (t *groupTrait) SetCategoryDefault(v model.GroupCategory) *groupTrait {
	t.updates = append(t.updates, t.mutation.categoryDefaultMutateFunc(v))
	return t
}

// SetCategoryFactory register a factory function and assign return value to Category, you can also use related factory's Create/CreateV as input function here
func (t *groupTrait) SetCategoryFactory(fn func(ctx context.Context) (model.GroupCategory, error)) *groupTrait {
	t.updates = append(t.updates, t.mutation.categoryFactoryMutateFunc(fn))
	return t
}

// SetAfterCreateFunc register a function to be called after struct create
func (f *GroupMetaFactory) SetAfterCreateFunc(fn func(ctx context.Context, i *model.Group) error) *GroupMetaFactory {
	f.mutation.afterCreateFunc = fn
	return f
}

// SetBeforeCreateFunc register a function to be called before struct create
func (f *GroupMetaFactory) SetBeforeCreateFunc(fn func(ctx context.Context, i *model.Group) error) *GroupMetaFactory {
	f.mutation.beforeCreateFunc = fn
	return f
}

// SetAfterCreateFunc register a function to be called after struct create
func (t *groupTrait) SetAfterCreateFunc(fn func(ctx context.Context, i *model.Group) error) *groupTrait {
	t.updates = append(t.updates, t.mutation.afterCreateMutateFunc(fn))
	return t
}

// SetBeforeCreateFunc register a function to be called before struct create
func (t *groupTrait) SetBeforeCreateFunc(fn func(ctx context.Context, i *model.Group) error) *groupTrait {
	t.updates = append(t.updates, t.mutation.beforeCreateMutateFunc(fn))
	return t
}

// Build create a  GroupFactory from GroupMetaFactory
func (f *GroupMetaFactory) Build() *GroupFactory {
	return &GroupFactory{meta: *f, counter: &Counter{}}
}

type GroupFactory struct {
	meta    GroupMetaFactory
	counter *Counter
}

// SetName set the Name field
func (f *GroupFactory) SetName(i string) *GroupBuilder {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}
	builder.SetName(i)

	return builder
}

// SetCategory set the Category field
func (f *GroupFactory) SetCategory(i model.GroupCategory) *GroupBuilder {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}
	builder.SetCategory(i)

	return builder
}

// Create return a new *model.Group
func (f *GroupFactory) Create(ctx context.Context) (*model.Group, error) {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}

	return builder.Create(ctx)
}

// CreateV return a new model.Group
func (f *GroupFactory) CreateV(ctx context.Context) (model.Group, error) {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}

	return builder.CreateV(ctx)
}

// CreateBatch return a []*model.Group slice
func (f *GroupFactory) CreateBatch(ctx context.Context, n int) ([]*model.Group, error) {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}

	return builder.CreateBatch(ctx, n)
}

// CreateBatchV return a []model.Group slice
func (f *GroupFactory) CreateBatchV(ctx context.Context, n int) ([]model.Group, error) {
	builder := &GroupBuilder{mutation: f.meta.mutation, counter: f.counter, factory: f}

	return builder.CreateBatchV(ctx, n)
}

type GroupBuilder struct {
	factory  *GroupFactory
	mutation groupMutation
	counter  *Counter

	nameOverride  string
	nameOverriden bool

	categoryOverride  model.GroupCategory
	categoryOverriden bool
}

// SetName set the Name field
func (b *GroupBuilder) SetName(i string) *GroupBuilder {
	b.nameOverride = i
	b.nameOverriden = true
	return b
}

// SetCategory set the Category field
func (b *GroupBuilder) SetCategory(i model.GroupCategory) *GroupBuilder {
	b.categoryOverride = i
	b.categoryOverriden = true
	return b
}

// CreateV return a new model.Group
func (b *GroupBuilder) CreateV(ctx context.Context) (model.Group, error) {
	var d model.Group
	p, err := b.Create(ctx)
	if err == nil {
		d = *p
	}
	return d, err
}

// Create return a new *model.Group
func (b *GroupBuilder) Create(ctx context.Context) (*model.Group, error) {

	var preSlice = []func(ctx context.Context, i *model.Group, c int) error{}
	var lazySlice = []func(ctx context.Context, i *model.Group, c int) error{}
	var postSlice = []func(ctx context.Context, i *model.Group, c int) error{}

	index := b.counter.Get()
	_ = index

	if b.nameOverriden {
		preSlice = append(preSlice, func(ctx context.Context, i *model.Group, c int) error {
			value := b.nameOverride

			i.Name = value
			return nil
		})
	} else {
		switch b.mutation.nameType {
		case TypeDefault:
			preSlice = append(preSlice, b.mutation.nameFunc)
		case TypeLazy:
			lazySlice = append(lazySlice, b.mutation.nameFunc)
		case TypeSequence:
			preSlice = append(preSlice, b.mutation.nameFunc)
		case TypeFactory:
			preSlice = append(preSlice, b.mutation.nameFunc)
		}
	}

	if b.categoryOverriden {
		preSlice = append(preSlice, func(ctx context.Context, i *model.Group, c int) error {
			value := b.categoryOverride

			i.Category = value
			return nil
		})
	} else {
		switch b.mutation.categoryType {
		case TypeDefault:
			preSlice = append(preSlice, b.mutation.categoryFunc)
		case TypeLazy:
			lazySlice = append(lazySlice, b.mutation.categoryFunc)
		case TypeSequence:
			preSlice = append(preSlice, b.mutation.categoryFunc)
		case TypeFactory:
			preSlice = append(preSlice, b.mutation.categoryFunc)
		}
	}

	v := &model.Group{}

	for _, f := range preSlice {

		err := f(ctx, v, index)

		if err != nil {
			return nil, err
		}
	}
	for _, f := range lazySlice {

		err := f(ctx, v, index)

		if err != nil {
			return nil, err
		}
	}
	if b.mutation.beforeCreateFunc != nil {
		if err := b.mutation.beforeCreateFunc(ctx, v); err != nil {
			return nil, err
		}
	}

	new := v

	if b.mutation.afterCreateFunc != nil {
		err := b.mutation.afterCreateFunc(ctx, new)
		if err != nil {
			return nil, err
		}
	}
	for _, f := range postSlice {
		err := f(ctx, new, index)
		if err != nil {
			return nil, err
		}
	}

	return new, nil
}
func (b *GroupBuilder) CreateBatch(ctx context.Context, n int) ([]*model.Group, error) {
	var results []*model.Group
	for i := 0; i < n; i++ {
		d, err := b.Create(ctx)
		if err != nil {
			return results, err
		}
		results = append(results, d)
	}
	return results, nil
}
func (b *GroupBuilder) CreateBatchV(ctx context.Context, n int) ([]model.Group, error) {
	var results []model.Group
	for i := 0; i < n; i++ {
		d, err := b.CreateV(ctx)
		if err != nil {
			return results, err
		}
		results = append(results, d)
	}
	return results, nil
}
