// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Ingredient is the predicate function for ingredient builders.
type Ingredient func(*sql.Selector)

// Recipe is the predicate function for recipe builders.
type Recipe func(*sql.Selector)

// RecipeIngredient is the predicate function for recipeingredient builders.
type RecipeIngredient func(*sql.Selector)

// Step is the predicate function for step builders.
type Step func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
