// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeRecipes holds the string denoting the recipes edge name in mutations.
	EdgeRecipes = "recipes"
	// Table holds the table name of the user in the database.
	Table = "users"
	// RecipesTable is the table that holds the recipes relation/edge.
	RecipesTable = "recipes"
	// RecipesInverseTable is the table name for the Recipe entity.
	// It exists in this package in order to avoid circular dependency with the "recipe" package.
	RecipesInverseTable = "recipes"
	// RecipesColumn is the table column denoting the recipes relation/edge.
	RecipesColumn = "user_recipes"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
